version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'nuget'
    directory: '/Jellyfin.Plugin.MediaPreview'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 5
    groups:
      nuget-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'nuget'
    directory: '/Jellyfin.Plugin.MediaPreview.Tests'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 5
    groups:
      nuget-test-minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
    commit-message:
      prefix: 'ci'
      include: 'scope'
