[changelog]
header = "# Changelog\n\n"
body = """
{% if version -%}
## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## Unreleased
{% endif %}

{% set features = commits | filter(attribute="group", value="Features") %}
{% set fixes = commits | filter(attribute="group", value="Fixes") %}
{% set builds = commits | filter(attribute="group", value="Build") %}
{% set docs = commits | filter(attribute="group", value="Documentation") %}
{% set refactors = commits | filter(attribute="group", value="Refactoring") %}
{% set other = commits | filter(attribute="group", value="Other") %}

{% if features | length > 0 %}
### Features
{% for commit in features %}
- {{ commit.message }}
{% endfor %}
{% endif %}
{% if fixes | length > 0 %}
### Fixes
{% for commit in fixes %}
- {{ commit.message }}
{% endfor %}
{% endif %}
{% if builds | length > 0 %}
### Build
{% for commit in builds %}
- {{ commit.message }}
{% endfor %}
{% endif %}
{% if docs | length > 0 %}
### Documentation
{% for commit in docs %}
- {{ commit.message }}
{% endfor %}
{% endif %}
{% if refactors | length > 0 %}
### Refactoring
{% for commit in refactors %}
- {{ commit.message }}
{% endfor %}
{% endif %}
{% if other | length > 0 %}
### Other
{% for commit in other %}
- {{ commit.message }}
{% endfor %}
{% endif %}

"""
trim = true
footer = ""

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"

[[git.commit_parsers]]
message = "^Prepare release .*"
skip = true

[[git.commit_parsers]]
message = "^Update changelog and manifest for v.*"
skip = true

[[git.commit_parsers]]
message = "^Merge branch .*"
skip = true

[[git.commit_parsers]]
message = "^Merge pull request .*"
skip = true

[[git.commit_parsers]]
message = "^ci"
skip = true

[[git.commit_parsers]]
message = "^feat"
group = "Features"

[[git.commit_parsers]]
message = "^fix"
group = "Fixes"

[[git.commit_parsers]]
message = "^build"
group = "Build"

[[git.commit_parsers]]
message = "^docs"
group = "Documentation"

[[git.commit_parsers]]
message = "^refactor"
group = "Refactoring"

[[git.commit_parsers]]
message = ".*"
group = "Other"
