export const mediaPreviewStyles = [
  '.jhs-preview-backdrop{position:absolute;inset:0;z-index:10;pointer-events:none;background:transparent;backdrop-filter:none;-webkit-backdrop-filter:none;display:none;border-radius:inherit;}',
  '.jhs-preview-layer{position:absolute;inset:0;z-index:20;pointer-events:none;opacity:1;background-repeat:no-repeat;background-position:0 0;background-color:transparent;overflow:hidden;border-radius:inherit;}',
  '.jhs-hover-countdown{position:absolute;z-index:24;display:none;width:34px;height:34px;border:0;border-radius:999px;background:conic-gradient(rgba(255,255,255,.42) calc(var(--progress,1)*1turn), rgba(255,255,255,.08) 0);box-shadow:0 8px 24px rgba(0,0,0,.28);pointer-events:none;overflow:hidden;}',
  '.jhs-hover-countdown.pos-top-left{top:10px;left:10px;}',
  '.jhs-hover-countdown.pos-top-right{top:10px;right:10px;}',
  '.jhs-hover-countdown.pos-bottom-left{bottom:10px;left:10px;}',
  '.jhs-hover-countdown.pos-bottom-right{bottom:10px;right:10px;}',
  '.jhs-hover-countdown-label{position:absolute;inset:2px;display:flex;align-items:center;justify-content:center;border-radius:999px;background:rgba(10,14,20,.76);color:rgba(255,255,255,.92);font-size:13px;font-weight:700;line-height:1;letter-spacing:.02em;backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);}',
  '.jhs-unavailable-message{position:absolute;left:50%;top:50%;z-index:26;display:none;max-width:calc(100% - 28px);padding:9px 14px;border-radius:999px;transform:translate(-50%,-50%);background:rgba(10,14,20,.76);color:rgba(232,236,242,.84);font-size:11px;font-weight:700;line-height:1.2;text-align:center;letter-spacing:.01em;border:1px solid rgba(255,255,255,.05);box-shadow:0 8px 24px rgba(0,0,0,.28);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);pointer-events:none;}',
  '.jhs-trailer-layer{position:absolute;inset:0;z-index:30;pointer-events:none;overflow:hidden;border-radius:inherit;background:transparent;display:none;}',
  '.jhs-trailer-actions{position:absolute;z-index:45;display:none;pointer-events:none;}',
  '.jhs-trailer-actions.pos-top-left{top:10px;left:10px;}',
  '.jhs-trailer-actions.pos-top-right{top:10px;right:10px;}',
  '.jhs-trailer-actions.pos-bottom-left{bottom:10px;left:10px;}',
  '.jhs-trailer-actions.pos-bottom-right{bottom:10px;right:10px;}',
  '.jhs-trailer-expand{display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;border:0;border-radius:999px;background:rgba(10,14,20,.76);color:#fff;box-shadow:0 8px 24px rgba(0,0,0,.28);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);cursor:pointer;pointer-events:auto;transition:transform .18s ease,background .18s ease,opacity .18s ease;}',
  '.jhs-trailer-expand:hover{transform:scale(1.06);background:rgba(22,28,38,.9);}',
  '.jhs-trailer-expand .material-icons{font-size:19px;line-height:1;}',
  '.jhs-trailer-layer.jhs-debug-visible{outline:2px solid rgba(0,255,255,.9);box-shadow:0 0 0 1px rgba(0,0,0,.6) inset;}',
  '.jhs-trailer-media{position:absolute;z-index:1;border:0;pointer-events:none;background:transparent;display:block;visibility:visible;opacity:1;}',
  '.jhs-progress{position:absolute;left:8px;right:8px;bottom:8px;z-index:90;height:3px;border-radius:999px;background:rgba(255,255,255,.18);pointer-events:none;overflow:hidden;}',
  '.jhs-progress-bar{height:100%;width:0;background:rgba(255,255,255,.88);transform-origin:left center;}',
  '.jhs-expanded-trailer-overlay{position:fixed;inset:0;z-index:10000;display:none;opacity:0;pointer-events:none;transition:opacity .24s ease;}',
  '.jhs-expanded-trailer-overlay.is-open{opacity:1;pointer-events:auto;}',
  '.jhs-expanded-trailer-backdrop{position:absolute;inset:0;background:rgba(5,8,14,.72);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);}',
  '.jhs-expanded-trailer-viewport{position:fixed;left:0;top:0;width:0;height:0;overflow:hidden;border-radius:22px;background:#000;box-shadow:0 24px 80px rgba(0,0,0,.45);transition:left .24s ease,top .24s ease,width .24s ease,height .24s ease,border-radius .24s ease;pointer-events:auto;}',
  '.jhs-expanded-trailer-media-host{position:absolute;inset:0;overflow:hidden;border-radius:inherit;pointer-events:auto;}',
  '.jhs-expanded-trailer-shell{position:absolute;inset:0;pointer-events:none;}',
  '.jhs-expanded-trailer-ui{position:absolute;top:20px;right:20px;left:20px;display:flex;align-items:center;justify-content:flex-end;gap:16px;z-index:2;pointer-events:none;}',
  '.jhs-expanded-trailer-title{display:none;}',
  '.jhs-expanded-trailer-close{display:inline-flex;align-items:center;justify-content:center;width:42px;height:42px;border:0;border-radius:999px;background:rgba(10,14,20,.76);color:#fff;box-shadow:0 10px 28px rgba(0,0,0,.28);cursor:pointer;pointer-events:auto;transition:transform .18s ease,background .18s ease;}',
  '.jhs-expanded-trailer-close:hover{transform:scale(1.06);background:rgba(22,28,38,.92);}',
  '.jhs-expanded-trailer-close .material-icons{font-size:22px;line-height:1;}',
  '.jhs-trailer-media.jhs-interactive{pointer-events:auto;}'
].join('');
