import type { PreviewResult, TrailerCandidate, TrickplayInfo } from './preview';

export interface CardState {
  hoverTimer: number | null;
  hoverCountdownFrame: number | null;
  hoverCountdownStartedAt: number | null;
  hoverCountdownDurationMs: number;
  hoverIntentAnchorX: number | null;
  hoverIntentAnchorY: number | null;
  leaveHoldTimer: number | null;
  lastPreviewEndedAt: number;
  pointerInside: boolean;
  previewActive: boolean;
  previewBackdrop: HTMLDivElement | null;
  previewFrame: HTMLDivElement | null;
  previewFrameSecondary: HTMLDivElement | null;
  activePreviewFrameSlot: 'primary' | 'secondary';
  previewTransitionTimer: number | null;
  hoverCountdown: HTMLDivElement | null;
  hoverCountdownLabel: HTMLSpanElement | null;
  unavailableMessage: HTMLDivElement | null;
  trailerLayer: HTMLDivElement | null;
  trailerActions: HTMLDivElement | null;
  trailerExpandButton: HTMLButtonElement | null;
  trailerMedia: HTMLVideoElement | HTMLIFrameElement | null;
  trailerMediaKind: 'video' | 'iframe' | null;
  trailerTransitionTimer: number | null;
  currentTrailer: TrailerCandidate | null;
  trailerPlaybackStartedAt: number;
  metadataOverlay: HTMLDivElement | null;
  metadataOverlayTitle: HTMLDivElement | null;
  metadataOverlayMeta: HTMLDivElement | null;
  progress: HTMLDivElement | null;
  progressBar: HTMLDivElement | null;
  lastPreviewKey: string | null;
  activePreviewSource: PreviewResult['source'] | null;
  lastMoveAt: number;
  queuedPercent: number | null;
  queuedMoveTimer: number | null;
  queuedMoveFrame: number | null;
  latestRequestToken: number;
  rootHost: HTMLElement | null;
  managedHostPosition: string | null;
  managedHostOverflow: string | null;
  autoScrubTimer: number | null;
  autoScrubPercent: number | null;
  autoScrubAnimationFrame: number | null;
  autoScrubStartedAt: number | null;
  currentTrickplayInfo: TrickplayInfo | null;
  lastRequestedTrickplayFrameIndex: number | null;
  lastRenderedTrickplayFrameIndex: number | null;
  lastTrickplayRenderAt: number;
  boundTarget: HTMLElement | null;
  boundHandlers: {
    onPointerEnter: (event: PointerEvent) => void;
    onPointerMove: (event: PointerEvent) => void;
    onPointerLeave: (event: PointerEvent) => void;
    onMouseEnter: (event: MouseEvent) => void;
    onMouseMove: (event: MouseEvent) => void;
    onMouseLeave: () => void;
    onPointerCancel: () => void;
    onContextMenu: () => void;
  } | null;
}
